# Google Drive 연동

In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

# 데이터 불러오기

In [2]:
import pandas as pd

DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/2024/한국SW기술진흥협회/Python기초통계/작업장_제3유형/기출문제/작업2유형/data/'

X_train = pd.read_csv(DATA_PATH + "titanic_reg_X_train.csv")
X_test = pd.read_csv(DATA_PATH + "titanic_reg_X_test.csv")
y_train = pd.read_csv(DATA_PATH + "titanic_reg_y_train.csv")

X_train.shape, X_test.shape, y_train.shape

((623, 11), (268, 11), (623, 1))

# 데이터 확인

In [3]:
X_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Cabin,Embarked
0,446,1,1,"Dodge, Master. Washington",male,4.0,0,2,33638,A34,S
1,651,0,3,"Mitkoff, Mr. Mito",male,NaN,0,0,349221,NaN,S
2,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.0,1,1,347742,NaN,S
3,451,0,2,"West, Mr. Edwy Arthur",male,36.0,1,2,C.A. 34651,NaN,S
4,315,0,2,"Hart, Mr. Benjamin",male,43.0,1,1,F.C.C. 13529,NaN,S

In [4]:
X_test.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Cabin,Embarked
0,710,1,3,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,NaN,C
1,440,0,2,"Kvillner, Mr. Johan Henrik Johannesson",male,31.0,0,0,C.A. 18723,NaN,S
2,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.0,0,0,SOTON/O2 3101287,NaN,S
3,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.0,0,1,248727,NaN,S
4,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,NaN,C

In [5]:
y_train.head(1)

      Fare
0  81.8583

# 결측치 확인

In [6]:
X_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            124
SibSp            0
Parch            0
Ticket           0
Cabin          484
Embarked         1
dtype: int64

In [7]:
X_test.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             53
SibSp            0
Parch            0
Ticket           0
Cabin          203
Embarked         1
dtype: int64

# 불필요한 컬럼 제거
- 패턴이 발견되지 않을 것 같은 컬럼 삭제
  + ID 컬럼 삭제

In [11]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'city': ['New York', 'Los Angeles', 'Chicago']
})

df

      name  age         city
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

## pop 메서드 활용

In [12]:
name_series = df.pop('name')
name_series.head(1)

0    Alice
Name: name, dtype: object

In [13]:
df.head()

   age         city
0   25     New York
1   30  Los Angeles
2   35      Chicago

In [14]:
X_train_ID = X_train.pop('PassengerId')
X_test_ID = X_test.pop('PassengerId')

In [15]:
X_train.head(1)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Cabin,Embarked
0,1,1,"Dodge, Master. Washington",male,4.0,0,2,33638,A34,S

In [16]:
X_test.head(1)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Cabin,Embarked
0,1,3,"Moubarek, Master. Halim Gonios (""William George"")",male,NaN,1,1,2661,NaN,C

# 컬럼분리

In [17]:
import numpy as np

cat_cols = X_train.select_dtypes(exclude = np.number).columns.tolist()
num_cols = X_train.select_dtypes(include = np.number).columns.tolist()

print(cat_cols, num_cols)

['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'] ['Survived', 'Pclass', 'Age', 'SibSp', 'Parch']

# 데이터셋 분리
- 훈련데이터와 검증데이터 분리

In [18]:
from sklearn.model_selection import train_test_split

X_tr, X_val, y_tr, y_val = train_test_split(
    X_train, y_train['Fare'],
    test_size=0.3,
    random_state=42
)

X_tr.shape, X_val.shape, y_tr.shape, y_val.shape

((436, 10), (187, 10), (436,), (187,))

# Pipeline 모델
- 결측치가 포함된 모델 훈련