In [1]:
# Tuple 정의 
x=(1,2)
type(x)

tuple

In [2]:
x

(1, 2)

In [3]:
# list와 tuple의 가장 큰 차이점 
# x[2]=4  observation을 추가하는 것이 불가능하다.

TypeError: 'tuple' object does not support item assignment

In [4]:
# x.append(5)   append를 사용해서 값을 추가하는 것이 불가능하다.

AttributeError: 'tuple' object has no attribute 'append'

In [5]:
animals=['dog', 'cat', 'bird']
for i in animals:
    print(i)

dog
cat
bird

In [6]:
k=len(animals) # animals 리스트 내의 값의 갯수를 저장한다.  length : 길이 
k

3

In [7]:
# range(3) : 처음부터 3번째까지가 아니고 , 2번째까지 0, 1, 2번 (이렇게 3개가 나오게 된다) 
for i in range(k):
    print(animals[i])

dog
cat
bird

In [8]:
# while을 이용해서도 loop를 실행할 수 있다. 
i=1
while i<5:
    print(i)
    i=i+1

1
2
3
4

In [10]:
# 0-9까지 숫자를 2를 매번 곱해서 리스트로 생성하자. 
# 0, 2, 4, 6, 8, 10, 12, 14, 16, 18
y=[] # 비어 있는 리스트 object 
for i in range(10):
    x=i*2
    y.append(x)
print(y)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
# list comprehension을 사용하면 같은 결과를 간단한 코드로 쓸 수 있다.

In [11]:
y1=[2*x for x in range(10)]
y1

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [12]:
from urllib.request import urlopen   # request package 
from bs4 import BeautifulSoup  # bs4 package
import pandas as pd

In [16]:
ServiceKey="29jTU1S%2B7bDI1Rb2LV0S5D0d3Xn%2Fji9T3k%2FWjsLR%2FyI9O3wEU0atKsr9hj9ATsfIpKgWmV8k8Ll67O%2F73Nyj6w%3D%3D"
month=202401 # 2024년 1월 거래 정보를 사용하고자 한다. 
gu_code=11110 # 서울시 종로구 데이터를 사용하겠다. 
numOfRows=1000  # 최대 1000개 거래정보를 가져오겠다. 
url="http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade?LAWD_CD="+str(gu_code)+"&DEAL_YMD="+str(month)+"&numOfRows="+str(numOfRows)+"&serviceKey="+ServiceKey

In [17]:
print(url)

http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade?LAWD_CD=11110&DEAL_YMD=202401&numOfRows=1000&serviceKey=29jTU1S%2B7bDI1Rb2LV0S5D0d3Xn%2Fji9T3k%2FWjsLR%2FyI9O3wEU0atKsr9hj9ATsfIpKgWmV8k8Ll67O%2F73Nyj6w%3D%3D

In [18]:
result=urlopen(url)
house=BeautifulSoup(result, 'lxml-xml')
house

<?xml version="1.0" encoding="utf-8"?>
<response><header><resultCode>00</resultCode><resultMsg>NORMAL SERVICE.</resultMsg></header><body><items><item><거래금액>     192,000</거래금액><거래유형>중개거래</거래유형><건축년도>2004</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 내수동</법정동><아파트>경희궁의아침3단지</아파트><월>1</월><일>13</일><전용면적>149</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>72</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>     192,000</거래금액><거래유형>중개거래</거래유형><건축년도>2004</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 내수동</법정동><아파트>경희궁의아침3단지</아파트><월>1</월><일>13</일><전용면적>149</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>72</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>      42,000</거래금액><거래유형>중개거래</거래유형><건축년도>2003</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 익선동</법정동><아파트>현대뜨레비앙</아파트><월>1</월><일>30</일><전용면적>48.54</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>55</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>      46,000</거래금액><거래유형>중개거래</거래유형><건축년도>2003</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 명륜1가</법정동><아파트>리치캐슬아파트</아파트><월>1</월><일>4</일><전용면적>64.68</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>33-85</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>      57,400</거래금액><거래유형>중개거래</거래유형><건축년도>2003</건축년도><년>2024</년><동> </동><등기일자>24.02.05</등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 명륜1가</법정동><아파트>송림아마레스아파트</아파트><월>1</월><일>26</일><전용면적>75.62</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>2-12</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>      57,500</거래금액><거래유형>중개거래</거래유형><건축년도>1993</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>1</월><일>8</일><전용면적>64.66</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>      13,500</거래금액><거래유형>중개거래</거래유형><건축년도>2014</건축년도><년>2024</년><동>삼전솔하임4차</동><등기일자>24.01.25</등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 숭인동</법정동><아파트>삼전솔하임4차</아파트><월>1</월><일>9</일><전용면적>15.09</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>318-2</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>      95,000</거래금액><거래유형>중개거래</거래유형><건축년도>2008</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>1</월><일>19</일><전용면적>84.92</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>     101,300</거래금액><거래유형>중개거래</거래유형><건축년도>2009</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>1</월><일>19</일><전용면적>84.9478</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>      80,000</거래금액><거래유형>중개거래</거래유형><건축년도>2009</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>1</월><일>27</일><전용면적>59.9426</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>     200,000</거래금액><거래유형>중개거래</거래유형><건축년도>2017</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 평동</법정동><아파트>경희궁자이(3단지)</아파트><월>1</월><일>27</일><전용면적>84.8359</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>233</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>     195,000</거래금액><거래유형>중개거래</거래유형><건축년도>2017</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 홍파동</법정동><아파트>경희궁자이(2단지)</아파트><월>1</월><일>18</일><전용면적>84.8359</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>199</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>     200,000</거래금액><거래유형>중개거래</거래유형><건축년도>2017</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 홍파동</법정동><아파트>경희궁자이(2단지)</아파트><월>1</월><일>22</일><전용면적>84.614</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>199</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>     156,000</거래금액><거래유형>중개거래</거래유형><건축년도>2017</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 홍파동</법정동><아파트>경희궁자이(2단지)</아파트><월>1</월><일>24</일><전용면적>59.8547</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>199</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>     135,000</거래금액><거래유형>직거래</거래유형><건축년도>2009</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 평창동</법정동><아파트>롯데캐슬로잔</아파트><월>1</월><일>22</일><전용면적>191.725</전용면적><중개사소재지> </중개사소재지><지번>108</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>      70,500</거래금액><거래유형>중개거래</거래유형><건축년도>1996</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 평창동</법정동><아파트>일성빌라트</아파트><월>1</월><일>27</일><전용면적>84.99</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>145-5</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>      39,000</거래금액><거래유형>중개거래</거래유형><건축년도>2011</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 무악동</법정동><아파트>무악다온채</아파트><월>1</월><일>29</일><전용면적>33.76</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>66-1</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item><item><거래금액>     101,000</거래금액><거래유형>중개거래</거래유형><건축년도>2008</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>1</월><일>29</일><전용면적>59.993</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item></items><numOfRows>1000</numOfRows><pageNo>1</pageNo><totalCount>18</totalCount></body></response>

In [19]:
te=house.find_all("item")
te

[<item><거래금액>     192,000</거래금액><거래유형>중개거래</거래유형><건축년도>2004</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 내수동</법정동><아파트>경희궁의아침3단지</아파트><월>1</월><일>13</일><전용면적>149</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>72</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>     192,000</거래금액><거래유형>중개거래</거래유형><건축년도>2004</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 내수동</법정동><아파트>경희궁의아침3단지</아파트><월>1</월><일>13</일><전용면적>149</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>72</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>      42,000</거래금액><거래유형>중개거래</거래유형><건축년도>2003</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 익선동</법정동><아파트>현대뜨레비앙</아파트><월>1</월><일>30</일><전용면적>48.54</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>55</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>      46,000</거래금액><거래유형>중개거래</거래유형><건축년도>2003</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 명륜1가</법정동><아파트>리치캐슬아파트</아파트><월>1</월><일>4</일><전용면적>64.68</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>33-85</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>      57,400</거래금액><거래유형>중개거래</거래유형><건축년도>2003</건축년도><년>2024</년><동> </동><등기일자>24.02.05</등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 명륜1가</법정동><아파트>송림아마레스아파트</아파트><월>1</월><일>26</일><전용면적>75.62</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>2-12</지번><지역코드>11110</지역코드><층>5</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>      57,500</거래금액><거래유형>중개거래</거래유형><건축년도>1993</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 창신동</법정동><아파트>창신쌍용2</아파트><월>1</월><일>8</일><전용면적>64.66</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>703</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>      13,500</거래금액><거래유형>중개거래</거래유형><건축년도>2014</건축년도><년>2024</년><동>삼전솔하임4차</동><등기일자>24.01.25</등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 숭인동</법정동><아파트>삼전솔하임4차</아파트><월>1</월><일>9</일><전용면적>15.09</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>318-2</지번><지역코드>11110</지역코드><층>15</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>      95,000</거래금액><거래유형>중개거래</거래유형><건축년도>2008</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 숭인동</법정동><아파트>종로센트레빌</아파트><월>1</월><일>19</일><전용면적>84.92</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>2-1</지번><지역코드>11110</지역코드><층>2</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>     101,300</거래금액><거래유형>중개거래</거래유형><건축년도>2009</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>1</월><일>19</일><전용면적>84.9478</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>13</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>      80,000</거래금액><거래유형>중개거래</거래유형><건축년도>2009</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 숭인동</법정동><아파트>종로청계힐스테이트</아파트><월>1</월><일>27</일><전용면적>59.9426</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>766</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>     200,000</거래금액><거래유형>중개거래</거래유형><건축년도>2017</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 평동</법정동><아파트>경희궁자이(3단지)</아파트><월>1</월><일>27</일><전용면적>84.8359</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>233</지번><지역코드>11110</지역코드><층>14</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>     195,000</거래금액><거래유형>중개거래</거래유형><건축년도>2017</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 홍파동</법정동><아파트>경희궁자이(2단지)</아파트><월>1</월><일>18</일><전용면적>84.8359</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>199</지번><지역코드>11110</지역코드><층>12</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>     200,000</거래금액><거래유형>중개거래</거래유형><건축년도>2017</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 홍파동</법정동><아파트>경희궁자이(2단지)</아파트><월>1</월><일>22</일><전용면적>84.614</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>199</지번><지역코드>11110</지역코드><층>4</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>     156,000</거래금액><거래유형>중개거래</거래유형><건축년도>2017</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 홍파동</법정동><아파트>경희궁자이(2단지)</아파트><월>1</월><일>24</일><전용면적>59.8547</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>199</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>     135,000</거래금액><거래유형>직거래</거래유형><건축년도>2009</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 평창동</법정동><아파트>롯데캐슬로잔</아파트><월>1</월><일>22</일><전용면적>191.725</전용면적><중개사소재지> </중개사소재지><지번>108</지번><지역코드>11110</지역코드><층>1</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>      70,500</거래금액><거래유형>중개거래</거래유형><건축년도>1996</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 평창동</법정동><아파트>일성빌라트</아파트><월>1</월><일>27</일><전용면적>84.99</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>145-5</지번><지역코드>11110</지역코드><층>3</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>      39,000</거래금액><거래유형>중개거래</거래유형><건축년도>2011</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 무악동</법정동><아파트>무악다온채</아파트><월>1</월><일>29</일><전용면적>33.76</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>66-1</지번><지역코드>11110</지역코드><층>9</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>,
 <item><거래금액>     101,000</거래금액><거래유형>중개거래</거래유형><건축년도>2008</건축년도><년>2024</년><동> </동><등기일자> </등기일자><매도자>개인</매도자><매수자>개인</매수자><법정동> 무악동</법정동><아파트>인왕산아이파크</아파트><월>1</월><일>29</일><전용면적>59.993</전용면적><중개사소재지>서울 종로구</중개사소재지><지번>60</지번><지역코드>11110</지역코드><층>11</층><해제사유발생일> </해제사유발생일><해제여부> </해제여부></item>]

In [21]:
data=[]
for i in range(len(te)):
    price=te[i].거래금액.string.strip()
    apt_name=te[i].아파트.string.strip()
    dong_name=te[i].법정동.string.strip()
    
    total=[price,apt_name, dong_name]
    data.append(total)

print(data)  #  list type의 데이터로 저장이 된다.

[['192,000', '경희궁의아침3단지', '내수동'], ['192,000', '경희궁의아침3단지', '내수동'], ['42,000', '현대뜨레비앙', '익선동'], ['46,000', '리치캐슬아파트', '명륜1가'], ['57,400', '송림아마레스아파트', '명륜1가'], ['57,500', '창신쌍용2', '창신동'], ['13,500', '삼전솔하임4차', '숭인동'], ['95,000', '종로센트레빌', '숭인동'], ['101,300', '종로청계힐스테이트', '숭인동'], ['80,000', '종로청계힐스테이트', '숭인동'], ['200,000', '경희궁자이(3단지)', '평동'], ['195,000', '경희궁자이(2단지)', '홍파동'], ['200,000', '경희궁자이(2단지)', '홍파동'], ['156,000', '경희궁자이(2단지)', '홍파동'], ['135,000', '롯데캐슬로잔', '평창동'], ['70,500', '일성빌라트', '평창동'], ['39,000', '무악다온채', '무악동'], ['101,000', '인왕산아이파크', '무악동']]

In [22]:
# 마지막으로 저장된 list "data"를 excel 또는 csv 파일로 내보낸다. 
# csv 파일로 저장해보자. 
# 1단계: list를 데이터 프레임으로 생성한다. pandas 의 data frame으로 변환한다. 
# 2단계: pandas data frame을 csv파일로 내보낸다. 
# data frame 이름을 temp로 지정한다. 
temp=pd.DataFrame(data, columns=['price', 'apt_name', 'dong_name']) # columns는 데이터 프레임에서 각 column의 이름을 지정한다. 
temp

      price    apt_name dong_name
0   192,000   경희궁의아침3단지       내수동
1   192,000   경희궁의아침3단지       내수동
2    42,000      현대뜨레비앙       익선동
3    46,000     리치캐슬아파트      명륜1가
4    57,400   송림아마레스아파트      명륜1가
5    57,500       창신쌍용2       창신동
6    13,500     삼전솔하임4차       숭인동
7    95,000      종로센트레빌       숭인동
8   101,300   종로청계힐스테이트       숭인동
9    80,000   종로청계힐스테이트       숭인동
10  200,000  경희궁자이(3단지)        평동
11  195,000  경희궁자이(2단지)       홍파동
12  200,000  경희궁자이(2단지)       홍파동
13  156,000  경희궁자이(2단지)       홍파동
14  135,000      롯데캐슬로잔       평창동
15   70,500       일성빌라트       평창동
16   39,000       무악다온채       무악동
17  101,000     인왕산아이파크       무악동

In [24]:
temp.to_csv("c:/temp100/house_price100.csv")  # csv 파일을 열어보면 한글이 깨져보인다. 
# 그러나 해당 파일을 다시 python으로 불러오면 한글이 정상으로 나온다.

In [26]:
temp.to_csv("c:/temp100/house_price100.csv",encoding='utf-8-sig')  # csv 파일에서 한글이 깨져 보이는 것이 싫으신 분들은 encoding 옵션을 사용한다.